# Generated by Django 3.1.7 on 2021-02-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CamperConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('vehicle_description', models.TextField()),
                ('conversion_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('registered_vehicle_type', models.CharField(choices=[('P_VAN', 'Panel Van'), ('C_VAN_REFIT', 'Campervan Refit'), ('SPEC_VEH', 'Special Vehicle')], max_length=254)),
                ('transmission_type', models.CharField(choices=[('MT', 'Manual'), ('AT', 'Automatic')], max_length=254)),
                ('vehicle_length', models.IntegerField()),
                ('berths', models.IntegerField()),
                ('belted_seats', models.IntegerField()),
                ('max_weight', models.IntegerField()),
                ('unladen_weight_verified', models.BooleanField(default=False, null=True)),
                ('unladen_weight', models.IntegerField(blank=True)),
                ('main_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
