# Generated by Django 3.1.7 on 2021-02-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0002_auto_20210225_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electric',
            name='inverter',
        ),
        migrations.RemoveField(
            model_name='electric',
            name='leisure_battery',
        ),
        migrations.RemoveField(
            model_name='electric',
            name='mains_charger',
        ),
        migrations.RemoveField(
            model_name='electric',
            name='mains_electrics',
        ),
        migrations.RemoveField(
            model_name='electric',
            name='mains_sign_off',
        ),
        migrations.RemoveField(
            model_name='electric',
            name='solar_panel',
        ),
        migrations.RemoveField(
            model_name='electric',
            name='split_charge_relay',
        ),
        migrations.RemoveField(
            model_name='electric',
            name='twelve_volt_electrics',
        ),
        migrations.RemoveField(
            model_name='electric',
            name='usb_sockets',
        ),
    ]
