# Generated by Django 3.1.7 on 2021-02-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0003_auto_20210225_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='electric',
            name='name',
            field=models.CharField(default='default', max_length=254),
            preserve_default=False,
        ),
    ]
