# Generated by Django 3.1.7 on 2021-03-03 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0005_auto_20210303_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camperconversion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversions.category'),
        ),
    ]
