# Generated by Django 3.1.7 on 2021-03-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0006_auto_20210303_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='camperconversion',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
