# Generated by Django 3.1.7 on 2021-02-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0007_auto_20210226_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camperconversion',
            name='unladen_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
