# Generated by Django 3.1.7 on 2021-03-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0007_camperconversion_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camperconversion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
