# Generated by Django 3.1.7 on 2021-03-06 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_savedlistings'),
        ('conversions', '0008_auto_20210304_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='camperconversion',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
    ]
