# Generated by Django 3.1.7 on 2021-03-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0009_camperconversion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
