# Generated by Django 3.1.7 on 2021-03-10 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0011_auto_20210309_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='camperconversion',
            name='unique_ref',
            field=models.CharField(default=uuid.uuid4, max_length=10),
        ),
    ]
