# Generated by Django 3.1.7 on 2021-04-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0015_auto_20210310_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='camperconversion',
            name='current_mileage',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
