# Generated by Django 3.1.7 on 2021-04-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0019_auto_20210409_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camperconversion',
            name='vehicle_length',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
