# Generated by Django 3.1.7 on 2021-04-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0022_auto_20210422_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camperconversion',
            name='vehicle_length',
            field=models.IntegerField(),
        ),
    ]
